// VoiceFlow C API - Auto-generated by cbindgen

#ifndef VOICEFLOW_H
#define VOICEFLOW_H

/* Warning: this file was auto-generated by cbindgen. Don't modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to the VoiceFlow pipeline
 */
typedef struct VoiceFlowHandle VoiceFlowHandle;

/**
 * Result struct returned to foreign callers
 */
typedef struct VoiceFlowResult {
  bool success;
  char *formatted_text;
  char *raw_transcript;
  char *error_message;
  uint64_t transcription_ms;
  uint64_t llm_ms;
  uint64_t total_ms;
} VoiceFlowResult;

/**
 * Initialize the VoiceFlow pipeline
 *
 * # Safety
 * config_path must be a valid null-terminated string or null for default
 */
struct VoiceFlowHandle *voiceflow_init(const char *configPath);

/**
 * Process audio samples and return formatted text
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - audio_data must point to audio_len floats (16kHz mono PCM)
 * - context can be null
 */
struct VoiceFlowResult voiceflow_process(struct VoiceFlowHandle *handle,
                                         const float *audioData,
                                         uintptr_t audioLen,
                                         const char *context);

/**
 * Free a VoiceFlowResult's strings
 *
 * # Safety
 * Only call this once per result
 */
void voiceflow_free_result(struct VoiceFlowResult result);

/**
 * Cleanup and free the handle
 *
 * # Safety
 * Only call this once per handle
 */
void voiceflow_destroy(struct VoiceFlowHandle *handle);

/**
 * Get the library version
 */
const char *voiceflow_version(void);

/**
 * Model info struct for FFI
 */
typedef struct ModelInfo {
    char *id;
    char *display_name;
    char *filename;
    float size_gb;
    bool is_downloaded;
} ModelInfo;

/**
 * Get the models directory path
 */
char *voiceflow_models_dir(void);

/**
 * Get the number of available models
 */
uintptr_t voiceflow_model_count(void);

/**
 * Get model info by index
 *
 * # Safety
 * index must be < voiceflow_model_count()
 */
struct ModelInfo voiceflow_model_info(uintptr_t index);

/**
 * Free model info strings
 *
 * # Safety
 * Only call once per ModelInfo
 */
void voiceflow_free_model_info(struct ModelInfo info);

/**
 * Free a C string returned by other functions
 *
 * # Safety
 * Only call once per string
 */
void voiceflow_free_string(char *s);

/**
 * Get the current model ID from config
 */
char *voiceflow_current_model(void);

/**
 * Set the current model in config (requires restart to take effect)
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_set_model(const char *model_id);

/**
 * Get the HuggingFace download URL for a model
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
char *voiceflow_model_download_url(const char *model_id);

// =============================================================================
// STT Engine Management
// =============================================================================

/**
 * Get the current STT engine ("whisper", "moonshine", or "qwen3-asr")
 */
char *voiceflow_current_stt_engine(void);

/**
 * Set the current STT engine ("whisper", "moonshine", or "qwen3-asr")
 *
 * # Safety
 * engine_id must be a valid null-terminated string
 */
bool voiceflow_set_stt_engine(const char *engine_id);

/**
 * Get the current Moonshine model ("tiny" or "base")
 */
char *voiceflow_current_moonshine_model(void);

/**
 * Set the current Moonshine model ("tiny" or "base")
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_set_moonshine_model(const char *model_id);

/**
 * Moonshine model info struct for FFI
 */
typedef struct MoonshineModelInfo {
    char *id;
    char *display_name;
    uint32_t size_mb;
    bool is_downloaded;
} MoonshineModelInfo;

/**
 * Get the number of available Moonshine models
 */
uintptr_t voiceflow_moonshine_model_count(void);

/**
 * Get Moonshine model info by index
 *
 * # Safety
 * index must be < voiceflow_moonshine_model_count()
 */
struct MoonshineModelInfo voiceflow_moonshine_model_info(uintptr_t index);

/**
 * Free Moonshine model info strings
 *
 * # Safety
 * Only call once per MoonshineModelInfo
 */
void voiceflow_free_moonshine_model_info(struct MoonshineModelInfo info);

/**
 * Check if a Moonshine model is downloaded
 *
 * # Safety
 * model_id must be a valid null-terminated string ("tiny" or "base")
 */
bool voiceflow_moonshine_model_downloaded(const char *model_id);

/**
 * Get the Moonshine models directory path
 */
char *voiceflow_moonshine_models_dir(void);

// =============================================================================
// Pipeline Mode and Consolidated Model Management
// =============================================================================

/**
 * Consolidated model info struct for FFI
 */
typedef struct ConsolidatedModelInfo {
    char *id;
    char *display_name;
    char *dir_name;
    float size_gb;
    bool is_downloaded;
} ConsolidatedModelInfo;

/**
 * Get the current pipeline mode ("stt-plus-llm" or "consolidated")
 */
char *voiceflow_current_pipeline_mode(void);

/**
 * Set the pipeline mode ("stt-plus-llm" or "consolidated")
 *
 * # Safety
 * mode must be a valid null-terminated string
 */
bool voiceflow_set_pipeline_mode(const char *mode);

/**
 * Get the current consolidated model ID
 */
char *voiceflow_current_consolidated_model(void);

/**
 * Set the consolidated model
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_set_consolidated_model(const char *model_id);

/**
 * Get the number of available consolidated models
 */
uintptr_t voiceflow_consolidated_model_count(void);

/**
 * Get consolidated model info by index
 *
 * # Safety
 * index must be < voiceflow_consolidated_model_count()
 */
struct ConsolidatedModelInfo voiceflow_consolidated_model_info(uintptr_t index);

/**
 * Free consolidated model info strings
 *
 * # Safety
 * Only call once per ConsolidatedModelInfo
 */
void voiceflow_free_consolidated_model_info(struct ConsolidatedModelInfo info);

/**
 * Check if a consolidated model is downloaded
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_consolidated_model_downloaded(const char *model_id);

/**
 * Get the directory path for a consolidated model
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
char *voiceflow_consolidated_model_dir(const char *model_id);

// =============================================================================
// VLM (Vision-Language Model) Management
// =============================================================================

/**
 * VLM model info struct for FFI
 */
typedef struct VlmModelInfo {
    char *id;
    char *display_name;
    char *dir_name;
    float size_gb;
    bool is_downloaded;
} VlmModelInfo;

/**
 * Get the number of available VLM models
 */
uintptr_t voiceflow_vlm_model_count(void);

/**
 * Get VLM model info by index
 */
struct VlmModelInfo voiceflow_vlm_model_info(uintptr_t index);

/**
 * Free VLM model info strings
 */
void voiceflow_free_vlm_model_info(struct VlmModelInfo info);

/**
 * Check if a VLM model is downloaded
 */
bool voiceflow_vlm_model_downloaded(const char *model_id);

/**
 * Get the HuggingFace repo for a VLM model
 */
char *voiceflow_vlm_model_hf_repo(const char *model_id);

/**
 * Get the number of required files for a VLM model
 */
uintptr_t voiceflow_vlm_model_file_count(const char *model_id);

/**
 * Get a required file name for a VLM model by index
 */
char *voiceflow_vlm_model_file_name(const char *model_id, uintptr_t index);

/**
 * Get the directory path for a VLM model
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
char *voiceflow_vlm_model_dir(const char *model_id);

/**
 * Get the current VLM model ID from config, or null if none selected
 */
char *voiceflow_current_vlm_model(void);

/**
 * Set the current VLM model in config (requires restart to take effect)
 * Pass null to clear the VLM selection (revert to LLM-only mode)
 */
bool voiceflow_set_vlm_model(const char *model_id);

// =============================================================================
// Post-Processing
// =============================================================================

/**
 * Apply post-processing to text (tokenization fix, voice commands, spelled words, replacements).
 * Used by consolidated mode where MLX Swift handles inference but Rust handles post-processing.
 *
 * # Safety
 * text must be a valid null-terminated string
 */
char *voiceflow_post_process_text(const char *text);

/**
 * Process pre-transcribed text through post-processing + LLM formatting.
 * Used when an external STT engine (e.g. Qwen3-ASR) provides the raw transcript.
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - text must be a valid null-terminated string
 * - context can be null
 */
struct VoiceFlowResult voiceflow_format_text(struct VoiceFlowHandle *handle,
                                              const char *text,
                                              const char *context);

/**
 * Check if the current STT engine is external (handled outside Rust pipeline)
 */
bool voiceflow_is_external_stt(void);

/**
 * Check if the current config is in consolidated mode
 */
bool voiceflow_is_consolidated_mode(void);

// =============================================================================
// Memory Management and Cleanup
// =============================================================================

/**
 * Memory info struct for FFI
 */
typedef struct MemoryInfo {
    uintptr_t resident_bytes;
    uintptr_t virtual_bytes;
    uintptr_t peak_bytes;
} MemoryInfo;

/**
 * Unload all models from memory (LLM and STT)
 * Call this before app termination or when switching models
 *
 * # Safety
 * handle must be a valid pointer from voiceflow_init
 */
void voiceflow_unload_models(struct VoiceFlowHandle *handle);

/**
 * Reset the LLM engine, allowing re-initialization on next use
 *
 * # Safety
 * handle must be a valid pointer from voiceflow_init
 */
void voiceflow_reset_llm(struct VoiceFlowHandle *handle);

/**
 * Get approximate memory usage in bytes
 */
uintptr_t voiceflow_memory_usage(void);

/**
 * Get detailed memory information
 */
struct MemoryInfo voiceflow_memory_info(void);

/**
 * Force a garbage collection hint
 */
void voiceflow_force_gc(void);

/**
 * Prepare for app shutdown - ensures clean resource release
 * Call this before NSApp.terminate() for clean shutdown
 */
void voiceflow_prepare_shutdown(void);

#endif  /* VOICEFLOW_H */
