// VoiceFlow C API - Auto-generated by cbindgen

#ifndef VOICEFLOW_H
#define VOICEFLOW_H

/* Warning: this file was auto-generated by cbindgen. Don't modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to the VoiceFlow pipeline
 */
typedef struct VoiceFlowHandle VoiceFlowHandle;

/**
 * Result struct returned to foreign callers
 */
typedef struct VoiceFlowResult {
  bool success;
  char *formatted_text;
  char *raw_transcript;
  char *error_message;
  uint64_t transcription_ms;
  uint64_t llm_ms;
  uint64_t total_ms;
} VoiceFlowResult;

/**
 * Model info struct for FFI
 */
typedef struct ModelInfo {
  char *id;
  char *display_name;
  char *filename;
  float size_gb;
  bool is_downloaded;
} ModelInfo;

/**
 * Moonshine model info struct for FFI
 */
typedef struct MoonshineModelInfo {
  char *id;
  char *display_name;
  uint32_t size_mb;
  bool is_downloaded;
} MoonshineModelInfo;

/**
 * Consolidated model info struct for FFI
 */
typedef struct ConsolidatedModelInfo {
  char *id;
  char *display_name;
  char *dir_name;
  float size_gb;
  bool is_downloaded;
} ConsolidatedModelInfo;

/**
 * C function pointer type for streaming token callbacks.
 * Returns true to continue generation, false to abort.
 */
typedef bool (*TokenCallbackFn)(const char *token, void *userdata);

/**
 * Memory info struct for FFI
 */
typedef struct MemoryInfo {
  uintptr_t resident_bytes;
  uintptr_t virtual_bytes;
  uintptr_t peak_bytes;
} MemoryInfo;

/**
 * Initialize the VoiceFlow pipeline
 *
 * # Safety
 * config_path must be a valid null-terminated string or null for default
 */
struct VoiceFlowHandle *voiceflow_init(const char *configPath);

/**
 * Process audio samples and return formatted text
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - audio_data must point to audio_len floats (16kHz mono PCM)
 * - context can be null
 */
struct VoiceFlowResult voiceflow_process(struct VoiceFlowHandle *handle,
                                         const float *audioData,
                                         uintptr_t audioLen,
                                         const char *context);

/**
 * Free a VoiceFlowResult's strings
 *
 * # Safety
 * Only call this once per result
 */
void voiceflow_free_result(struct VoiceFlowResult result);

/**
 * Cleanup and free the handle
 *
 * # Safety
 * Only call this once per handle
 */
void voiceflow_destroy(struct VoiceFlowHandle *handle);

/**
 * Get the library version
 */
const char *voiceflow_version(void);

/**
 * Classify the intent of a transcribed utterance.
 *
 * Returns a JSON string describing the intent (verbatim / inline correction /
 * retroactive correction / one of the AI commands), plus an optional anchor
 * hint when the utterance was an unambiguous "X to Y" / "X, not Y" form.
 * Caller must free via `voiceflow_free_string`.
 *
 * # Safety
 * `text` must be a valid null-terminated UTF-8 string. Returns null on
 * parse / serialization failure.
 */
char *voiceflow_classify_intent(const char *text);

/**
 * Run an AI voice command (rewrite / proofread / shorten / bullet / continue /
 * summarize / reply / explain / draft / question).
 *
 * `input_json` is a JSON-encoded `CommandInput`:
 * ```json
 * { "command": "rewrite", "parameter": "more formal",
 *   "selection": "...", "field_text": "...", "field_source": "ax" }
 * ```
 *
 * Returns the LLM's prose output as JSON `{"output":"...","abstained":bool}`.
 * Caller must free via `voiceflow_free_string`. Returns null on error.
 *
 * # Safety
 * `handle` must be a valid pointer from `voiceflow_init`.
 * `input_json` must be a valid null-terminated UTF-8 string.
 */
char *voiceflow_run_ai_command(struct VoiceFlowHandle *handle, const char *inputJson);

/**
 * Run retroactive correction.
 *
 * `input_json` is a JSON-encoded `RetroactiveInput`:
 * ```json
 * { "field_text": "...", "field_source": "ax|browser|shadow|ocr",
 *   "recent_insertions": ["...", "..."], "user_utterance": "..." }
 * ```
 *
 * Returns the LLM's structured `Edit` as a JSON string the Swift side
 * parses and applies. Caller must free via `voiceflow_free_string`.
 * Returns null on error (handle null, JSON malformed, LLM unavailable).
 *
 * # Safety
 * `handle` must be a valid pointer from `voiceflow_init`.
 * `input_json` must be a valid null-terminated UTF-8 string.
 */
char *voiceflow_retroactive_correct(struct VoiceFlowHandle *handle, const char *inputJson);

/**
 * Assess whether a freshly-transcribed utterance is a redo (replace) of the
 * previous dictated output, or new content to append.
 *
 * `input_json` is a JSON-encoded `RedoInput`:
 * ```json
 * { "previous_output": "...", "new_transcript": "...", "context": "..." }
 * ```
 *
 * Returns a `RedoDecision` as a JSON string ({ "replace": bool, "text":
 * string, "confidence": number }) the Swift side parses. Caller must free via
 * `voiceflow_free_string`. Returns null on error.
 *
 * # Safety
 * `handle` must be a valid pointer from `voiceflow_init`.
 * `input_json` must be a valid null-terminated UTF-8 string.
 */
char *voiceflow_assess_redo(struct VoiceFlowHandle *handle, const char *inputJson);

/**
 * Get the models directory path
 */
char *voiceflow_models_dir(void);

/**
 * Get the number of available models
 */
uintptr_t voiceflow_model_count(void);

/**
 * Get model info by index
 *
 * # Safety
 * index must be < voiceflow_model_count()
 */
struct ModelInfo voiceflow_model_info(uintptr_t index);

/**
 * Free model info strings
 *
 * # Safety
 * Only call once per ModelInfo
 */
void voiceflow_free_model_info(struct ModelInfo info);

/**
 * Free a C string returned by other functions
 *
 * # Safety
 * Only call once per string
 */
void voiceflow_free_string(char *s);

/**
 * Get the current model ID from config
 */
char *voiceflow_current_model(void);

/**
 * Set the current model in config (requires restart to take effect)
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_set_model(const char *modelId);

/**
 * Get the HuggingFace download URL for a model
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
char *voiceflow_model_download_url(const char *modelId);

/**
 * Get the current STT engine ("whisper", "moonshine", or "qwen3-asr")
 */
char *voiceflow_current_stt_engine(void);

/**
 * Set the current STT engine ("whisper", "moonshine", or "qwen3-asr")
 *
 * # Safety
 * engine_id must be a valid null-terminated string
 */
bool voiceflow_set_stt_engine(const char *engineId);

/**
 * Get the current Moonshine model ("tiny" or "base")
 */
char *voiceflow_current_moonshine_model(void);

/**
 * Set the current Moonshine model ("tiny" or "base")
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_set_moonshine_model(const char *modelId);

/**
 * Get the number of available Moonshine models
 */
uintptr_t voiceflow_moonshine_model_count(void);

/**
 * Get Moonshine model info by index
 *
 * # Safety
 * index must be < voiceflow_moonshine_model_count()
 */
struct MoonshineModelInfo voiceflow_moonshine_model_info(uintptr_t index);

/**
 * Free Moonshine model info strings
 *
 * # Safety
 * Only call once per MoonshineModelInfo
 */
void voiceflow_free_moonshine_model_info(struct MoonshineModelInfo info);

/**
 * Check if a Moonshine model is downloaded
 *
 * # Safety
 * model_id must be a valid null-terminated string ("tiny" or "base")
 */
bool voiceflow_moonshine_model_downloaded(const char *modelId);

/**
 * Get the Moonshine models directory path
 */
char *voiceflow_moonshine_models_dir(void);

/**
 * Get the current pipeline mode ("stt-plus-llm" or "consolidated")
 */
char *voiceflow_current_pipeline_mode(void);

/**
 * Set the pipeline mode ("stt-plus-llm" or "consolidated")
 *
 * # Safety
 * mode must be a valid null-terminated string
 */
bool voiceflow_set_pipeline_mode(const char *mode);

/**
 * Get the current consolidated model ID
 */
char *voiceflow_current_consolidated_model(void);

/**
 * Set the consolidated model
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_set_consolidated_model(const char *modelId);

/**
 * Get the number of available consolidated models
 */
uintptr_t voiceflow_consolidated_model_count(void);

/**
 * Get consolidated model info by index
 *
 * # Safety
 * index must be < voiceflow_consolidated_model_count()
 */
struct ConsolidatedModelInfo voiceflow_consolidated_model_info(uintptr_t index);

/**
 * Free consolidated model info strings
 *
 * # Safety
 * Only call once per ConsolidatedModelInfo
 */
void voiceflow_free_consolidated_model_info(struct ConsolidatedModelInfo info);

/**
 * Check if a consolidated model is downloaded
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_consolidated_model_downloaded(const char *modelId);

/**
 * Get the directory path for a consolidated model
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
char *voiceflow_consolidated_model_dir(const char *modelId);

/**
 * Get the mmproj filename for the current model, or null if not multimodal
 */
char *voiceflow_model_mmproj_filename(void);

/**
 * Get the mmproj download URL for the current model, or null if not multimodal
 */
char *voiceflow_model_mmproj_download_url(void);

/**
 * Check if the mmproj file is downloaded for the current model
 */
bool voiceflow_model_mmproj_downloaded(void);

/**
 * Get the mmproj size in GB for the current model
 */
float voiceflow_model_mmproj_size_gb(void);

/**
 * Process pre-transcribed text with an image through post-processing + multimodal LLM formatting.
 * Used for visual context dictation (Control+Option+Space hotkey).
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - text must be a valid null-terminated string
 * - context can be null
 * - image_data must point to image_len bytes of JPEG data (or null for text-only)
 */
struct VoiceFlowResult voiceflow_process_text_with_image(struct VoiceFlowHandle *handle,
                                                         const char *text,
                                                         const char *context,
                                                         const uint8_t *imageData,
                                                         uintptr_t imageLen);

/**
 * Add a user-learned correction to the replacement dictionary.
 * The correction is applied deterministically by the Rust pipeline's replacement step.
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - original and corrected must be valid null-terminated strings
 */
bool voiceflow_add_replacement(struct VoiceFlowHandle *handle,
                               const char *original,
                               const char *corrected);

/**
 * Remove a user-learned correction from the replacement dictionary.
 * Call this when the user deletes a correction from the UI so it stops being applied immediately.
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - original must be a valid null-terminated string
 */
bool voiceflow_remove_replacement(struct VoiceFlowHandle *handle, const char *original);

/**
 * Apply post-processing to text (tokenization fix, voice commands, spelled words, replacements).
 * Used by consolidated mode where MLX Swift handles inference but Rust handles post-processing.
 *
 * # Safety
 * text must be a valid null-terminated string
 */
char *voiceflow_post_process_text(const char *text);

/**
 * Process pre-transcribed text through post-processing + LLM formatting.
 * Used when an external STT engine (e.g. Qwen3-ASR Python daemon) provides the raw transcript
 * and we want the traditional pipeline's LLM formatting applied.
 *
 * Returns a VoiceFlowResult with formatted_text and raw_transcript.
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - text must be a valid null-terminated string
 * - context can be null
 */
struct VoiceFlowResult voiceflow_format_text(struct VoiceFlowHandle *handle,
                                             const char *text,
                                             const char *context);

/**
 * Process pre-transcribed text through deterministic normalization (no LLM).
 * Uses the fast text_normalize pipeline instead of LLM formatting.
 * Returns a VoiceFlowResult with formatted_text and raw_transcript.
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - text must be a valid null-terminated string
 */
struct VoiceFlowResult voiceflow_format_text_deterministic(struct VoiceFlowHandle *handle,
                                                           const char *text);

/**
 * Process audio directly through an audio-native model (e.g., Gemma 4).
 * Bypasses the separate STT step — the LLM handles both transcription and formatting.
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - audio_data must be a valid pointer to float samples (16kHz mono PCM)
 * - audio_len must be the number of samples
 * - context may be null
 */
struct VoiceFlowResult voiceflow_process_audio_direct(struct VoiceFlowHandle *handle,
                                                      const float *audioData,
                                                      uintptr_t audioLen,
                                                      const char *context);

/**
 * Process pre-transcribed text through post-processing + LLM formatting with streaming.
 * Each generated token is delivered to the callback as it's produced.
 * Returns a VoiceFlowResult with the fully post-processed formatted_text.
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - text must be a valid null-terminated string
 * - context can be null
 * - callback must be a valid function pointer
 * - userdata is passed through to the callback unchanged
 */
struct VoiceFlowResult voiceflow_format_text_streaming(struct VoiceFlowHandle *handle,
                                                       const char *text,
                                                       const char *context,
                                                       TokenCallbackFn callback,
                                                       void *userdata);

/**
 * Check if the current STT engine is external (handled outside Rust pipeline)
 */
bool voiceflow_is_external_stt(void);

/**
 * Check if the current config is in consolidated mode
 */
bool voiceflow_is_consolidated_mode(void);

/**
 * Check if the current config is in audio-direct mode
 */
bool voiceflow_is_audio_direct_mode(void);

/**
 * Unload all models from memory (LLM and STT)
 * Call this before app termination or when switching models
 *
 * # Safety
 * handle must be a valid pointer from voiceflow_init
 */
void voiceflow_unload_models(struct VoiceFlowHandle *handle);

/**
 * Reset the LLM engine, allowing re-initialization on next use
 *
 * # Safety
 * handle must be a valid pointer from voiceflow_init
 */
void voiceflow_reset_llm(struct VoiceFlowHandle *handle);

/**
 * Unload the STT engine from memory
 * Call this when streaming replaces STT to free memory
 *
 * # Safety
 * handle must be a valid pointer from voiceflow_init
 */
void voiceflow_unload_stt(struct VoiceFlowHandle *handle);

/**
 * Get approximate memory usage in bytes
 * This is a rough estimate based on tracked allocations
 */
uintptr_t voiceflow_memory_usage(void);

/**
 * Get detailed memory information
 */
struct MemoryInfo voiceflow_memory_info(void);

/**
 * Force a garbage collection hint
 * On Rust, this mainly drops any cached allocator memory
 */
void voiceflow_force_gc(void);

/**
 * Prepare for app shutdown - ensures clean resource release
 * Call this before NSApp.terminate() for clean shutdown
 */
void voiceflow_prepare_shutdown(void);

#endif  /* VOICEFLOW_H */
